name: Daily Morning Market Report

on:
  schedule:
    # Run at 6:00 AM EST (11:00 AM UTC) Monday-Friday
    - cron: '0 11 * * 1-5'
  workflow_dispatch:  # Allow manual trigger for testing

env:
  MAVEN_OPTS: "-Xmx1024m"

jobs:
  generate-morning-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Create reports directory
      run: mkdir -p reports
    
    - name: Compile Java application
      run: mvn clean compile
    
    - name: Run morning report generator
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        WORK_EMAIL_LIST: ${{ secrets.WORK_EMAIL_LIST }}
      run: mvn exec:java -Dexec.mainClass="com.marketreport.MorningReportGenerator"
    
    - name: Commit and push report
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reports/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily morning report - $(date +'%Y-%m-%d %H:%M EST')"
          git push
        fi
    
    - name: Upload report artifact
      uses: actions/upload-artifact@v3
      with:
        name: morning-report-$(date +'%Y%m%d')
        path: reports/morning_report_*.html
        retention-days: 30

  # Test job that runs on pull requests
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Compile and test
      run: |
        mvn clean compile
        mvn test
